### PR TITLE
purge page when comment was approved

### PR DESCRIPTION
**Pull request by shaula**
When a comment status changes, then the respective page should be purged (works in an environment where each comment has to be approved).

### CODE REVIEW

**Comment by Ipstenu** [comment]
This should be totally unnecessary. The plugin does this via the edit_post action

> Runs when a post or page is updated/edited, including when a comment is added or updated (which causes the comment count for the post to update).

So that should cover it. Are you using other plugins to mess with comments? I tested on a vanilla WP and it behaves as designed.

Also URL params aren't supposed to be cached by Varnish anyway, so you're doing something odd with your Varnish Rules.

**Comment by shaula** [comment]
Did not know about the behavior of edit_post action. You're right.

Regarding GET parameters: I think any GET resource should be cacheable. On the one hand Wordpress could be used with GET params ?p=123 as well as without (pretty Urls). On the other hand ajax requests using GET parameters should be cached by Varnish if requested so by the backend (i.e. if the backend script sets appropriate caching headers).

In my vcl_hash function I got: `hash_data(req.url);`
...and this req.url also includes GET parameters. So, nothing fancy here I guess.

**Comment by Ipstenu** [comment]
On the other hand, though, a GET resource could also be a nonce (not something you want to cache) or a unique string to identify a subscription change. They're really tricky :/

Also the plugin will alert you "I don't work without pretty permalinks" ;)

I'm going to test the query string and see if causes other weirdness. It shouldn't HURT anything but thinking about what query params are used for with WordPress, it's an odd thing to need.

**Comment by Ipstenu** [comment]
Closing this, since the query URL one is the right one to follow.

**Pull request closed without merging**
